version: "3.8"
services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 5432:5432
    expose:
      - "5432"
    volumes:
      - db-data:/var/lib/postgresql/data:cached
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      dockerfile: Dockerfile
    command: bash -c "alembic upgrade head && python app/main.py"
    tty: true
    volumes:
      - ./app:/app/:cached
    environment:
      PYTHONPATH: .
      DATABASE_URL: "postgresql+asyncpg://user:password@postgres:5432/db"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8000:8000

volumes:
  db-data: